# Generated by Django 3.2 on 2021-05-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Каталог курсов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dateend',
            field=models.DateTimeField(verbose_name='Дата конца курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='datestart',
            field=models.DateTimeField(verbose_name='Дата старта курса'),
        ),
    ]
